config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

    get 'welcome/index'
    
    resources :articles do
        resources :comments
    end
    
    root 'welcome#index'
    
   
    post '/signup', to: 'users#create'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
  
    resources :users    
    

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy
    validates :title, presence: true,
                        length: 
                                {
                                    minimum: 5
                                }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
      validates :password, presence: true, length: { minimum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
include SessionsHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
     
def index
    @articles = Article.all
end
def show
    @article = Article.find(params[:id])
end

def new
  @article = Article.new
end

def edit
    @article = Article.find(params[:id])
end
    
def create
  @article = Article.new(article_params)
 
  if @article.save
    redirect_to @article
  else
    render 'new'
  end
end
    
def update
  @article = Article.find(params[:id])
 
  if @article.update(article_params)
    redirect_to @article
  else
    render 'edit'
  end
end

def destroy
    @article = Article.find(params[:id])
    @article.destroy
    
    redirect_to articles_path
end
 
private
  def article_params
    params.require(:article).permit(:title, :text)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
    def show
        @article = Article.find(params[:id])
    end
    
    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article)
    end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    


end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end


    def log_out
    session.delete(:user_id)
    @current_user = nil
  end
    
  def logged_in?
      !current_user.nil?

  end
end

app/helpers/users_helper.rb
module UsersHelper


end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title,  class: 'form-control' %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text, class: 'form-control', :id => "message_area", :rows => 10 %>

  </p>
 
  <p>
   <%= f.submit class: 'form-control pull-right' %>
  </p>
    

<% end %>

app/views/articles/_navigation.html.erb
  <nav id="mainNav" class="navbar  navbar-fixed-top navbar-inverse">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">MY BLOG</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right ">
                    <li>
                       <%= link_to 'Home' ,  controller: 'articles' %>
                    </li>
                    <li>
                       <%= link_to 'About', '/' %>
                    </li>
                    <li>
                        <%= link_to 'Contact', '/' %>
                    </li>
                    <li>
                        <%= link_to 'Blog', articles_path %>
                    </li>
                  
                    <% if logged_in? %>
                      <li>
                        <%= link_to 'New Article', new_article_path %>
                    </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                          Account <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                          <li><%= link_to "Profile", current_user %></li>
                          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                          <li class="divider"></li>
                          <li>
                            <%= link_to "Log out", logout_path, method: :delete %>
                          </li>
                        </ul>
                      </li>
                    <% else %>
                    <li>
                        <%= link_to 'Login', "", data: {toggle: "modal", target: "#login_modal"} %>

                    </li>
                    <li>
                        <%= link_to 'Signup', "", data: {toggle: "modal", target: "#myModal"} %>
                    </li>
               <% end %>
                </ul>
            </div>
        </div>
    </nav>

    <%= render 'welcome/login_modal' %>
    <%= render 'welcome/sign_up_modal' %>





       

app/views/articles/edit.html.erb
<div>
    <br> 
    <br>
    <div class = "container">
       <header class="intro-header" style="background-image: url('img/about-bg.jpg')">
                <div class = "jumbotron">
                    <div class="row">
                        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                            <div class="page-heading">
                                <h1>Edit Article</h1>
                                <hr class="small">
                            <!--<span class="subheading">This is what I do.</span>-->
                            </div>
                        </div>
                    </div>
                </div>
        </header>
    <br>
  
            
            <div class="myBackground">
                <%= render 'form' %>
                <%= form_for(@article) do |f| %>
                <br>
                <br> 

            </div>
            <br>
                
        <div class = "pull-right">
            <button>
                <%= link_to 'Back', articles_path %> 
            </button> 
            
            </div>
        <% end %>
            
</div>

app/views/articles/index.html.erb
<div>
    <br> 
    <br>
    <div class = "container">
       <header class="intro-header" style="background-image: url('img/about-bg.jpg')">
                <div class = "jumbotron">
                    <div class="row">
                        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                            <div class="page-heading">
                                <h1>Listing Articles</h1>
                                <hr class="small">
                            </div>
                        </div>
                    </div>
                </div>
        </header>
   
    
    
    <br>
  
            <% @articles.each do |article| %>
            <div class="myBackground">
            <h1><%= article.title %></h1>
            <p>
              <td><%= article.text %></td>
            </p>
                <div>
                    <span class="badge">Posted 2012-08-02 20:47:04</span>
                    <div class="pull-right">
                        <a class='btn btn-primary btn-xs' href="#">
                            <span class="glyphicon glyphicon-zoom-in">
                            <%= link_to 'Show', article_path(article) %>
                            </span>
                        </a> 
                        <a class='btn btn-info btn-xs' href="#">
                            <span class="glyphicon glyphicon-edit">
                            <%= link_to 'Edit', edit_article_path(article) %>
                            </span> 
                        </a> 
                         <a href="#" class="btn btn-danger btn-xs">         <span class="glyphicon glyphicon-remove">     <%= link_to 'Destroy', article_path(article),
                                method: :delete, 
                                data: 
                                    {confirm: 'Are you sure?' } %>
                            </span>
                        </a>
                       
                    </div>         
                 </div>
            <br>
            </div>
            <br>
            <% end %>
    </div>

    
    
    
    
    
    
    
    
    
    
    
    
</div>

app/views/articles/new.html.erb
<div>
    <br> 
    <br>
    <div class = "container">
       <header class="intro-header" style="background-image: url('img/about-bg.jpg')">
                <div class = "jumbotron">
                    <div class="row">
                        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                            <div class="page-heading">
                                <h1>New Article</h1>
                                <hr class="small">
                            <!--<span class="subheading">This is what I do.</span>-->
                            </div>
                        </div>
                    </div>
                </div>
        </header>
    <br>
  
            
            <div class="myBackground">
                <%= render 'form' %>
                <br> <br>
            </div>
            <br>
                
        <div class = "pull-right">
            <button>
                <%= link_to 'Back', articles_path %> 
            </button> 
            
            </div>
            
</div>

app/views/articles/show.html.erb
<div>
    <br> 
    <br>
    <div class = "container">
       <header class="intro-header">
                <div class = "jumbotron">
                    <div class="row">
                        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                            <div class="page-heading">
                                <h2>
                                    <%= @article.title %>
                                </h2>
                                <hr class="small">
                            <!--<span class="subheading">This is what I do.</span>-->
                            </div>
                        </div>
                    </div>
                </div>
        </header>
    <br>
  
            
            <div class="myBackground">
               <%= @article.text %>

                <br>
                <br> 

            </div>
            <br>
        
        <div class = "myBackground">
            <h4>Comments:</h4>
            <hr>
            <%= render @article.comments %>

            <h4>Add a comment:</h4>
            <%= render 'comments/form' %>
            
                <div class = "pull-right">
                <%= link_to 'Edit', edit_article_path(@article) %> |
                <%= link_to 'Back', articles_path %> 
                </div>  
              <br> <br>
        </div>
                
          
</div>
</div>

app/views/comments/_comment.html.erb
    <div class = "myBackground2">
        <p>
          <strong>Commenter:</strong>
          <%= comment.commenter %>
        <br>
          <strong>Comment:</strong>
          <%= comment.body %>
        </p>

        <p class = "small">
          <%= link_to 'Delete Comment', [comment.article, comment],
                       method: :delete,
                       data: { confirm: 'Are you sure?' } %>
        </p>


</div>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body , class: 'form-control' ,:rows => 5 %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : " BLOG" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Bootstrap" %>">
   
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id= "page-top">
            <%= render 'articles/navigation' %>
            <br> <br> 
          <div>
              <%= yield %>
          </div>
        
  </body>
</html>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

<div>
    <br> 
    <br>
    <div class = "container">
       <header class="intro-header" style="background-image: url('img/about-bg.jpg')">
                <div class = "jumbotron">
                    <div class="row">
                        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                            <div class="page-heading">
                                <h1> EDIT PROFILE</h1>
                                <hr class="small">
                            <!--<span class="subheading">This is what I do.</span>-->
                            </div>
                        </div>
                    </div>
                </div>
        </header>
    <br>
  
            
            <div class="myBackground">
             <div class="row">
              <div class="col-md-6 col-md-offset-3">
                <%= form_for(@user) do |f| %>

                  <%= f.label :name %>
                  <%= f.text_field :name, class: 'form-control' %>

                  <%= f.label :email %>
                  <%= f.email_field :email, class: 'form-control' %>

                  <%= f.label :password %>
                  <%= f.password_field :password, class: 'form-control' %>

                  <%= f.label :password_confirmation, "Confirmation" %>
                  <%= f.password_field :password_confirmation, class: 'form-control' %>

                  <%= f.submit "Save changes", class: "btn btn-primary" %>
                <% end %>
              </div>
            </div>
            </div>
            <br>
                
        <div class = "pull-right">
            <button>
                <%= link_to 'Back', user_path %> 
            </button> 
            
            </div>
            
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div>
    <br> 
    <br>
    <% provide(:title, @user.name) %>

    <div class = "container">
       <header class="intro-header" style="background-image: url('img/about-bg.jpg')">
                <div class = "jumbotron">
                    <div class="row">
                        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                            <div class="page-heading">
                                <h1>User Profile</h1>
                                <hr class="small">
                            </div>
                        </div>
                    </div>
                </div>
        </header>
   
    
    
    <br>
            <div class="myBackground">
                <h1> <%= @user.name %> </h1>
                <p>
                  <td><%= @user.email %></td>
                </p>

                <br>
            </div>
            <br>
    </div>  
</div>

app/views/welcome/_login_modal.html.erb
<div class="modal fade" id="login_modal" tabindex="-1" role="dialog" aria-labelledby="login_modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">       
        
        <div class="modal-header">
            <button class="close" data-dismiss="modal">x</button>
            <h2>LOGIN</h2>
        </div>

        <div class="modal-body">
        <%= form_for(:session, url: login_path) do |f| %>

          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>

          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>

        </div>

        <div class="modal-footer">
                <div>
                              <%= f.submit "Log in", class: "btn btn-primary" %>

                    <p>New user? <%= link_to "Sign up now!", signup_path
%></p>
                <% end %>

                        </div>
                    </div>
                </div>
                        
             </div>
        </div>

app/views/welcome/_sign_up_modal.html.erb
 <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="signup_modal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button class="close" data-dismiss="modal">x</button>
                        <% provide(:title, 'Sign up') %>

                        <h2 class="modal-title" id="myModalLabel">
                            SIGN UP
                        </h2>
                    </div>
                    <div class="modal-body">
                            <%= form_for User.new, url:signup_path do |f| %>

                            <div>
                                <%= f.label :name %><br />
                                <%= f.text_field :name %>
                            </div>
                            <div>
                                <%= f.label :email %><br />
                                <%= f.email_field :email %>
                            </div>
                            <div>
                                <%= f.label :password %><br />
                                <%= f.password_field :password %>
                            </div>
                            <div>
                                <%= f.label :password_confirmation, "Password Confirmation" %><br />
                                <%= f.password_field :password_confirmation %>
                            </div>
                    </div>
                    <div class="modal-footer">
                       <div>
                            <%= f.submit "Sign up", :class => 'btn btn-success' %>
                               <% end %>

                        </div>
                    </div>
                </div>
                        
             </div>
        </div>

app/views/welcome/index.html.erb
    <header>
        <div class="container">
            <div class="row">
                <div>
                    <div class="site-heading">
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                           <div class="jumbotron">
                              <div class="container">
                                <h1>WELCOME</h1>
                                <hr>
                                <p>“The most important sentence in any article is the first one. If it doesn’t induce the reader to proceed to the second sentence, your article is dead. And if the second sentence doesn’t induce him to continue to the third sentence, it’s equally dead. Of such a progression of sentences, each tugging the reader forward until … safely hooked, a writer constructs that fateful unit: the lead.”</p>
                                
                                    <div  class="btn btn-primary btn-xl"> 
                                     <%= link_to 'Go to My Blog >>' ,  controller: 'articles' %>
                                     </div>
                               </div>
                            </div>                                 
                    </div>
                </div>
            </div>
        </div>
    </header>  